language: cpp
sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - 

  matrix:
    - CMAKE_BUILD_TYPE=Debug
      SHARED=ON
    - CMAKE_BUILD_TYPE=Debug
      SHARED=OFF
    - CMAKE_BUILD_TYPE=Release
      SHARED=ON
    - CMAKE_BUILD_TYPE=Release
      SHARED=OFF

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
    - ninja-build
    - qtbase5-dev

before_install:
  - |
    # Install cmake and ninja
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export QTDIR=/usr/lib/x86_64-linux-gnu/qt5
      export PATH="$QTDIR/bin:$PATH"
    else
      brew update > /dev/null
      brew tap homebrew/versions
      brew install ninja
      brew install qt
      export QTDIR="/usr/local/opt/qt5"
      export PATH="$QTDIR/bin:$PATH"
    fi

install:
  # Install GCC 6
  - |
    # Install GCC
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get -qq update
      travis_retry sudo apt-get -qq install gcc-6 g++-6
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    fi

# Clone examples: they are the code to test against.
  - git clone https://github.com/cmakespark/cmake.git ${HOME}/cmake
  - export CMAKESPARK=${HOME}/cmake
  - mkdir /tmp/installed

script:
  - |
    # Build and install simplelib
    mkdir /tmp/simplelib-build
    cd /tmp/simplelib-build
    cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DBUILD_SHARED_LIBS=${SHARED} -DCMAKE_INSTALL_PREFIX=/tmp/installed -G Ninja ${TRAVIS_BUILD_DIR}/simplelib
    cmake --build . --target all
    cmake --build . --target install
    cmake --build . --target sdk
  - |
    # Relocate library
    cp -r /tmp/installed /tmp/relocated
 
  - |
    # Build and install Simpleapp
    mkdir /tmp/simpleapp-build
    cd /tmp/simpleapp-build
    cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=/tmp/installed -DCC1simplelib_DIR=/tmp/relocated/lib/cmake/CC1simplelib -G Ninja ${TRAVIS_BUILD_DIR}/simpleapp
    cmake --build . --target all
    cmake --build . --target install

  - |
    # Build and install QSimpleApp
    mkdir /tmp/QSimpleApp-build
    cd /tmp/QSimpleApp-build
    cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=/tmp/installed -DCC1simplelib_DIR=/tmp/relocated/lib/cmake/CC1simplelib -G Ninja ${TRAVIS_BUILD_DIR}/QSimpleApp
    cmake --build . --target all
    cmake --build . --target install

  - |
    # Build and install complex lib
    mkdir /tmp/complexlib-build
    cd /tmp/complexlib-build
    cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DBUILD_SHARED_LIBS=${SHARED} -DCMAKE_INSTALL_PREFIX=/tmp/installed -G Ninja ${TRAVIS_BUILD_DIR}/complexlib
    cmake --build . --target all
    cmake --build . --target test
    cmake --build . --target install
    cmake --build . --target sdk

